apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubernetes-project
  name: kubernetes-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-project
  template:
    metadata:
      labels:
        app: kubernetes-project
    spec:
      containers:
      - image: 00397/kubernetes-project
        name: kubernetes-project